spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employees?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath:mybatis/mappings/*.xml

# 是否启用swagger。
# 只作为开发测试联调阶段使用。
swagger:
  enable: true

# tomcat作为war包容器时，该端口设置不起作用，以Tomcat的端口（server.xml）为准
#server:
#  port: 8095
#  servlet:
#    context-path: /
