server:
  port: 8080
  servlet:
    application-display-name: demo

spring:
  redis:
    timeout: 30000
    host: localhost
    port: 6379

# 测试spring integration 分布式锁
#zookeeper:
#  host: 172.168.0.21:2181