##########################
# Redis-集群模式配置-开始##
##########################
spring:
  redis:
    timeout: 30000
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    cluster:
      nodes: 192.168.23.114:6379,192.168.23.115:6379,192.168.23.116:6379,192.168.23.117:6379,192.168.23.118:6379,192.168.23.119:6379
      max-redirects: 3    # 获取失败最大重定向次数
##########################
# Redis-集群模式配置-结束##
##########################


server:
  port: 8097
