
##########################
## Redis-多个单机模式配置-开始##
#spring:
#  redis:
#    default:
#      timeout: 30000
#      host: localhost
#      port: 6379
#      password: 123456
#
#    localhost:
#      timeout: 30000
#      host: localhost
#      port: 6380
#      password: 123456

## Redis-多个单机模式配置-结束##
##########################


##########################
## Redis-多个单机模式+哨兵模式 配置-开始##

#spring:
#  redis:
#    connect-timeout: 30000
#    lettuce:
#      pool:
#        max-active: 1000
#        max-wait: -1
#        max-idle: 100
#        min-idle: 20
#    sentinel:
#      master: mymaster
#      nodes: 172.190.119.82:16379,172.190.119.82:16380,172.190.119.82:16381
#    password: root
#
#    default:
#      timeout: 30000
#      host: localhost
#      port: 6379
#      password: 123456
#
#    localhost:
#      timeout: 30000
#      host: localhost
#      port: 6380
#      password: 123456

## Redis-多个单机模式+哨兵模式 配置-结束##
##########################

server:
  port: 8097
