spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      strict: false
      datasource:
        master:
          url: jdbc:mysql://192.168.100.130:3306/springdemo?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: aA123456/
          driver-class-name: com.mysql.cj.jdbc.Driver

        mysql:
          url: jdbc:mysql://localhost:3306/zhulong?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456789
          driver-class-name: com.mysql.cj.jdbc.Driver

        others:
          url: jdbc:mysql://192.168.100.131:3306/employees?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: aA123456/
          driver-class-name: com.mysql.cj.jdbc.Driver

# 数据库密码 解密秘钥
jasypt:
  encryptor:
    password: demo
